Insert into BCMS
(ID ,ANY_PROJECTSPECIFIC_SOFTWARE_REQUIREMENT ,BACKUP_KEY_CONTACT ,DATA_REVIEWED_BY ,ECC_ACCOMODATION_NEEDED ,IS_WORKFROM_HOME_POSSIBLE ,
KEY_CONTACT ,NOOFKEYRESOURCESNEEDED ,PRIMARY_BUILDING ,PRIMARY_LOCATION ,RECOVERY_TIMELINES ,RELOCATION_BUILDING ,RELOCATION_LOCATION ,
REMARKS ,SERVICE_PRIORITY ,TRANSPORT_REQUIREMENTS ,TYPE_OF_PROJECT ,UNIT )
values(1234,'NA','987456','BNSF','N','N','698745','2','B5','Hyderabad','5days','B6','Bangalore','Dont Die','medium','NA','GOLD','RCL');

Insert into RESOURCES (RESOURCE_ID,NAME,CONTACT_NO ,ADDRESS  ,ID) values (648879,'ABHISHEK','9748782128','hyderabad',1234);
Insert into RESOURCES (RESOURCE_ID,NAME,CONTACT_NO ,ADDRESS  ,ID) values (1063674,'VAMSI','999999999','hyderabad',1234);

Insert into BCMS
(ID ,ANY_PROJECTSPECIFIC_SOFTWARE_REQUIREMENT ,BACKUP_KEY_CONTACT ,DATA_REVIEWED_BY ,ECC_ACCOMODATION_NEEDED ,IS_WORKFROM_HOME_POSSIBLE ,
KEY_CONTACT ,NOOFKEYRESOURCESNEEDED ,PRIMARY_BUILDING ,PRIMARY_LOCATION ,RECOVERY_TIMELINES ,RELOCATION_BUILDING ,RELOCATION_LOCATION ,
REMARKS ,SERVICE_PRIORITY ,TRANSPORT_REQUIREMENTS ,TYPE_OF_PROJECT ,UNIT )
values(1235,'NA','987456','BNSF','N','N','698745','2','B5','Hyderabad','5days','B6','Bangalore','Dont Die','medium','NA','GOLD','RCL');


Insert into RESOURCES (RESOURCE_ID,NAME,CONTACT_NO ,ADDRESS  ,ID) values (752734,'SHIVA','3693693693','hyderabad',1235);
Insert into RESOURCES (RESOURCE_ID,NAME,CONTACT_NO ,ADDRESS  ,ID) values (79683,'VENKI','1234567890','hyderabad',1235);
